name = "XGSessionServer"
version = "0.2.0"
description = "A microservice that handles user sessions and their information"
license = "MIT"
authors = [
    "Edson Manuel Carballo Vera <edsonmanuelcarballovera@gmail.com>",
]
maintainers = [
    "Edson Manuel Carballo Vera <edsonmanuelcarballovera@gmail.com>"
]